- name: "apt-get update"
  shell: "apt-get update"
  ignore_errors: yes
- name: "install software-properties-common"
  shell: "apt-get install -y software-properties-common apt-transport-https"
- name: "install tools via apt"
  shell: "DEBIAN_FRONTEND=noninteractive apt-get install -y gobuster ripgrep fd-find bat exa unicornscan crowbar parsero filezilla httpie jq htop"
- name: update tools via apt
  shell: "DEBIAN_FRONTEND=noninteractive apt-get install -y --only-upgrade code exploitdb tmux wget nano chromium firefox-esr"
