- name: "apt-get update"
  shell: "apt-get update"
  ignore_errors: yes
- name: "install apt dep"
  shell: "DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common apt-transport-https"
- name: "install tools via apt"
  shell: "DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-multilib gobuster ripgrep fd-find bat exa unicornscan crowbar parsero filezilla httpie jq htop sshuttle shellter"
- name: update tools via apt
  shell: "DEBIAN_FRONTEND=noninteractive apt-get install -y --only-upgrade exploitdb tmux wget nano chromium firefox-esr"
- name: check code installed
  shell: "which code"
  register: check_code
  failed_when: check_code.rc not in [0,1]
- block:
  - name: update code via apt
    shell: "DEBIAN_FRONTEND=noninteractive apt-get install -y --only-upgrade code"
  when: check_code.rc == 0
- name: "apt-get autoremove"
  shell: "DEBIAN_FRONTEND=noninteractive apt-get autoremove -y"
