- name: check code installed
  shell: "which code"
  register: check_code
  failed_when: check_code.rc not in [0,1]
- block:
  - name: microsoft.asc
    shell: "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg"
    become: no
  - name: microsoft.gpg
    shell: "sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/"
    become: no
  - name: vscode.list
    shell: "sudo sh -c 'echo \"deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main\" > /etc/apt/sources.list.d/vscode.list'"
    become: no
  - name: rm -f packages.microsoft.gpg
    shell: "rm -f packages.microsoft.gpg"
    become: no
  - name: "apt-get update"
    shell: "apt-get update"
    ignore_errors: yes
  - name: apt-get install -y code
    shell: "DEBIAN_FRONTEND=noninteractive apt-get install -y code"
  - name: install extension
    shell: "code --install-extension {{ item }}"
    become: no
    with_items:
      - christian-kohler.path-intellisense
      - ms-python.python
      - mikestead.dotenv
      - EditorConfig.EditorConfig
      - eamodio.gitlens
      - donjayamanne.githistory
      - esbenp.prettier-vscode
      - formulahendry.auto-close-tag
      - formulahendry.auto-rename-tag
      - HookyQR.beautify
      - ms-vscode.hexeditor
      - ms-vscode.powershell
      - oderwat.indent-rainbow
      - ritwickdey.LiveServer
      - usernamehw.errorlens
      - VisualStudioExptTeam.vscodeintellicode
      - pkief.material-icon-theme
      - github.github-vscode-theme
  when: check_code.rc == 1

- name: edit ~/Desktop/code.desktop
  become: no
  blockinfile:
    dest: ~/Desktop/code.desktop
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK code"
    content: |
      [Desktop Entry]
      Type=Application
      TryExec=code
      Exec=code
      Icon=code
      Terminal=false
      Categories=Utility;TextEditor;Development;IDE;

      Name=VSCode
      StartupWMClass=code
      Actions=new-empty-window;
      Keywords=vscode;

      [Desktop Action New]
      Name=Open code
      Exec=code
- name: chmod desktop
  shell: "chmod +x ~/Desktop/code.desktop"
  become: no

- name: edit ~/.config/Code/User/settings.json
  become: no
  blockinfile:
    dest: ~/.config/Code/User/settings.json
    create: true
    marker: "// {mark} ANSIBLE MANAGED BLOCK code"
    content: |
      {
        "diffEditor.wordWrap": "on",
        "editor.bracketPairColorization.enabled": true,
        "editor.fontFamily": "'Source Han Code JP', monospace",
        "editor.fontSize": 14,
        "editor.formatOnSave": false,
        "editor.minimap.renderCharacters": false,
        "editor.renderWhitespace": "all",
        "editor.snippetSuggestions": "top",
        "editor.suggestSelection": "first",
        "editor.tabSize": 2,
        "editor.wordWrap": "on",
        "explorer.confirmDelete": false,
        "explorer.confirmDragAndDrop": false,
        "files.exclude": {
          "**/._**": true,
          "**/.cache": true,
          "**/.classpath": true,
          "**/.DS_Store": true,
          "**/.factorypath": true,
          "**/.git": true,
          "**/.hg": true,
          "**/.idea": true,
          "**/.log": true,
          "**/.project": true,
          "**/.settings": true,
          "**/.sublime-project": true,
          "**/.sublime-workspace": true,
          "**/.svn": true,
          "**/.tmp": true,
          "**/.vs": true,
          "**/.vscode": true,
          "**/node_modules": true,
          "**/scss-lint-report.xml": true
        },
        "files.insertFinalNewline": true,
        "files.trimTrailingWhitespace": true,
        "files.watcherExclude": {
          "**/._**": true,
          "**/.cache": true,
          "**/.DS_Store": true,
          "**/.git": true,
          "**/.hg": true,
          "**/.idea": true,
          "**/.log": true,
          "**/.project": true,
          "**/.settings": true,
          "**/.sublime-project": true,
          "**/.sublime-workspace": true,
          "**/.svn": true,
          "**/.tmp": true,
          "**/.vs": true,
          "**/.vscode": true,
          "**/node_modules": true,
          "**/scss-lint-report.xml": true
        },
        "git.autofetch": true,
        "git.confirmSync": false,
        "git.enableSmartCommit": true,
        "terminal.integrated.fontFamily": "SauceCodePro Nerd Font",
        "terminal.integrated.fontSize": 13,
        "workbench.colorTheme": "GitHub Dark",
        "workbench.iconTheme": "material-icon-theme",
        "workbench.startupEditor": "welcomePage",
        "terminal.integrated.cursorStyle": "underline",
      }
