- name: rockyou.txt
  stat:
    path: /usr/share/wordlists/rockyou.txt
  register: rockyou_file
- block:
  - name: 7z x rockyou.txt
    shell: "7z x /usr/share/wordlists/rockyou.txt.gz -o/usr/share/wordlists/"
  when:
    - not rockyou_file.stat.exists
- name: add NS /etc/resolv.conf
  blockinfile:
    dest: /etc/resolv.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      nameserver 1.1.1.1
      nameserver 2606:4700:4700::1111
      nameserver 8.8.8.8
      nameserver 2001:4860:4860::8888
- name: "xfce workspace count 4"
  shell: "xfconf-query -c xfwm4 -p /general/workspace_count -s 4"
- name: edit  ~/.tmux.conf
  become: no
  blockinfile:
    dest: ~/.tmux.conf
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      set-option -g mouse on
