- name: check SauceCodePro
  stat:
    path: /usr/share/fonts/SauceCodePro
  register: SauceCodePro
  become: no
- block:
  - name: SauceCodePro dir
    file:
      path: /usr/share/fonts/SauceCodePro
      state: directory
      owner: root
      group: root
      mode: 0755
  - name: "wget SauceCodePro"
    shell: "wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/SourceCodePro.zip -O SourceCodePro.zip"
  - name: "7z x SauceCodePro"
    shell: "7z x SourceCodePro.zip -o/usr/share/fonts/SauceCodePro"
  - name: "rm SauceCodePro"
    shell: "rm SourceCodePro.zip"
  when:
    - not SauceCodePro.stat.exists

- name: check SourceHanCodeJP
  stat:
    path: /usr/share/fonts/SourceHanCodeJP
  register: SourceHanCodeJP
  become: no
- block:
  - name: SourceHanCodeJP dir
    file:
      path: /usr/share/fonts/SourceHanCodeJP
      state: directory
      owner: root
      group: root
      mode: 0755
  - name: "wget SourceHanCodeJP"
    shell: "wget https://github.com/adobe-fonts/source-han-code-jp/archive/refs/tags/2.012R.zip -O SourceHanCodeJP.zip"
  - name: "7z x SourceHanCodeJP"
    shell: "7z x SourceHanCodeJP.zip"
  - name: "mv SourceHanCodeJP"
    shell: "mv source-han-code-jp-2.012R/OTF /usr/share/fonts/SourceHanCodeJP"
  - name: "chmod SourceHanCodeJP"
    shell: "chmod 0755 /usr/share/fonts/SourceHanCodeJP/OTF"
  - name: "rm SourceHanCodeJP.zip"
    shell: "rm SourceHanCodeJP.zip"
  - name: "rm SourceHanCodeJP.zip"
    shell: "rm -rf source-han-code-jp-2.012R"
  when:
    - not SourceHanCodeJP.stat.exists
