- name: touch ~/.hushlogin
  shell: "touch ~/.hushlogin"
  become: no
- name: edit ~/.zshrc
  become: no
  blockinfile:
    dest: ~/.zshrc
    content: |
      alias ls='exa -lg --octal-permissions --time-style long-iso --icons'
      alias l='exa -lg --octal-permissions --time-style long-iso --icons'
      alias la='exa -lag --octal-permissions --time-style long-iso --icons'
      lt() {
          if [ "$1" != "" ]
          then
              exa -lT --icons --time-style=long-iso -L=$1
          else
              exa -lT --icons --time-style=long-iso -L=2
          fi
      }
      alias c='batcat --theme="OneHalfDark"'
      alias gr='rg'
      alias grl='rg -l'
      alias f='fdfind'
      alias ]='cd ../'
      alias de='cd ~/Desktop'
      alias dl='cd ~/Downloads'
      alias do='cd ~/Documents'
      alias tool='cd ~/tool'
      alias rmr='rm -rf'
      alias cl='clear'
      alias zshrc='code ~/.zshrc'
      chpwd() {
          if [[ $(pwd) != $HOME ]]; then;
              ls
          fi
      }
      alias g='git'
      alias gl='git pull'
      alias ga='git add --all'
      alias gc='git commit -m'
      alias gp='git push origin (git_current_branch)'
      alias commit='git add . ; git commit -m "commit" ; git push origin main'
      alias pipreq='pip install -r requirements.txt'
      alias venv='source venv/bin/activate'
      alias venvinit='rm -rf venv ; python -m venv venv'
      alias venvsetup='venvinit ; venv ; pip install -U pip ; pipreq'
