- name: check rustc
  stat:
    path: "~/.cargo"
  become: no
  register: check_rustc
- block:
    - name: "install tools"
      shell: "DEBIAN_FRONTEND=noninteractive apt-get install -y cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev"
    - name: rustup
      shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      become: no
  when: check_rustc.stat.exists == false

- name: check bin
  stat:
    path: "/usr/bin/alacritty"
  become: no
  register: check_bin
- block:
    - name: git clone
      shell: "git clone https://github.com/alacritty/alacritty.git ~/alacritty"
      become: no
    - name: build
      shell: "cd ~/alacritty ; ~/.cargo/bin/cargo build --release"
      become: no
    - name: mv /usr/bin
      shell: "sudo cp ~/alacritty/target/release/alacritty /usr/bin"
      become: no
    - name: rm ~/alacritty
      shell: "rm -rf ~/alacritty"
      become: no
  when: check_bin.stat.exists == false

- name: check desktop
  stat:
    path: "~/Desktop/Alacritty.desktop"
  become: no
  register: check_desktop
- block:
    - name: desktop
      shell: "cd ~/Desktop ; wget https://raw.githubusercontent.com/alacritty/alacritty/master/extra/linux/Alacritty.desktop"
      become: no
    - name: chmod desktop
      shell: "chmod +x ~/Desktop/Alacritty.desktop"
      become: no
  when: check_desktop.stat.exists == false

- name: edit ~/.alacritty.yml
  become: no
  blockinfile:
    dest: ~/.alacritty.yml
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK alacritty"
    content: |
      window:
        dimensions:
          columns: 110
          lines: 28
        padding:
          x: 3
          y: 3
        opacity: 1.0
      font:
        normal:
          family: "SauceCodePro Nerd Font"
          style: Regular
        offset:
          y: 1
        size: 10
      # https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/alacritty/Argonaut.yml
      colors:
        bright:
          black: '#444444'
          blue: '#0092ff'
          cyan: '#67fff0'
          green: '#abe15b'
          magenta: '#9a5feb'
          red: '#ff2740'
          white: '#ffffff'
          yellow: '#ffd242'
        cursor:
          cursor: '#ff0018'
          text: '#ff0018'
        normal:
          black: '#232323'
          blue: '#008df8'
          cyan: '#00d8eb'
          green: '#8ce10b'
          magenta: '#6d43a6'
          red: '#ff000f'
          white: '#ffffff'
          yellow: '#ffb900'
        primary:
          background: '#0e1019'
          foreground: '#fffaf4'
        selection:
          background: '#002a3b'
          text: '#ffffff'
      cursor:
        style:
          shape: Underline
      live_config_reload: true
